# Stage 1: Build the application
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
# Builds both browser (static) and server (SSR) files
RUN npm run build

# Stage 2: Production Server
FROM node:20-alpine
WORKDIR /app

# Copy the built output from the build stage. 
# (Replace 'your-app-name' with your actual project name from angular.json)
COPY --from=build /app/dist/sport-web ./dist/sport-web

# Set environment variables
ENV NODE_ENV=production
ENV PORT=4000
EXPOSE 4000

# Start the Node Express server generated by Angular SSR
CMD ["node", "dist/sport-web/server/server.mjs"]